import SwiftUI

// The branded start-up view ("Spotlight"): a plum radial background, a pink halo, the pig and, once it has bloomed in,
// the wordmark. Geometry comes from `BrandLayout` (generated by Tools/make-brand-assets.swift together with the launch
// image), so the first frame here is the launch screen and nothing jumps.
//
// It only ever shows while the app is genuinely starting (ContentView's `!initialRestoreFinished`): nothing waits for
// the animation, and when start-up ends first the view is simply cross-faded away.

struct BrandSplashView: View {
    /// The launch square's side in points: the same value the launch image was drawn at.
    #if os(tvOS)
    static let side: CGFloat = 1080
    #else
    static let side: CGFloat = 600
    #endif

    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @State private var glowScale: CGFloat = 1
    @State private var pigScale: CGFloat = 1
    @State private var wordIn = false
    @State private var slowStart = false

    private var showWord: Bool { wordIn || reduceMotion }

    var body: some View {
        let s = Self.side
        let pigW = BrandLayout.pigWidth * s
        let pigH = pigW * 797 / 1000
        let lift = showWord ? BrandLayout.groupLift * s : 0
        ZStack {
            Color("LaunchEdge")
            Image("BrandPlate").resizable().frame(width: s, height: s)
            // Everything in front of the plum lifts a little when the wordmark arrives (the group's mass stays centred).
            ZStack {
                Image("BrandGlow").resizable()
                    .frame(width: 2 * BrandLayout.glowRadius * s, height: 2 * BrandLayout.glowRadius * s)
                    .scaleEffect(glowScale)
                Image("PigLogo").resizable().frame(width: pigW, height: pigH)
                    .offset(x: (0.5 - BrandLayout.pigCentroidX) * pigW, y: (0.5 - BrandLayout.pigCentroidY) * pigH)
                    .scaleEffect(pigScale, anchor: UnitPoint(x: BrandLayout.pigCentroidX, y: BrandLayout.pigCentroidY))
                Image("BrandWordmark").resizable()
                    .frame(width: BrandLayout.wordmarkWidth * s, height: BrandLayout.wordmarkHeight * s)
                    .offset(y: (BrandLayout.wordmarkTop + BrandLayout.wordmarkHeight / 2) * s + (showWord ? 0 : 0.03 * s))
                    .opacity(showWord ? 1 : 0)
            }
            .frame(width: s, height: s)
            .offset(y: -lift)
            if slowStart {
                ProgressView().controlSize(.small).opacity(0.55)
                    .offset(y: s * 0.40)
                    .transition(.opacity)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .ignoresSafeArea()
        .accessibilityElement(children: .ignore)
        .accessibilityLabel("Starting PigTV")
        .task { await play() }
        .task {
            // A quiet progress indicator, only when start-up is genuinely slow.
            try? await Task.sleep(for: .seconds(2))
            if !Task.isCancelled { withAnimation(.easeIn(duration: 0.4)) { slowStart = true } }
        }
    }

    private func play() async {
        guard !reduceMotion else { return }
        // Glow blooms out and settles; the pig pops with an overshoot; then the wordmark rises in.
        withAnimation(.easeOut(duration: 0.3)) { glowScale = 1.14 }
        withAnimation(.easeOut(duration: 0.16)) { pigScale = 1.08 }
        try? await Task.sleep(for: .milliseconds(170))
        withAnimation(.spring(response: 0.42, dampingFraction: 0.5)) { pigScale = 1 }
        try? await Task.sleep(for: .milliseconds(130))
        withAnimation(.easeInOut(duration: 0.35)) { glowScale = 1 }
        try? await Task.sleep(for: .milliseconds(300))
        withAnimation(.easeOut(duration: 0.5)) { wordIn = true }
    }
}

#Preview { BrandSplashView() }
